import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Navigation & Branding
    dashboard: 'Dashboard',
    stock: 'Inventory Management',
    sales: 'Sales Operations',
    waitSystem: 'Credit Management',
    ledger: 'General Ledger',
    admin: 'System Control',
    logOut: 'Logout',
    liveSync: 'Sync',
    searchPlaceholder: 'Search assets...',
    inventoryHeader: 'Inventory Management',
    commandInterface: 'Management Console',
    systemArchitecture: 'Operational Framework',
    operationalDiagnostics: 'System Records',
    confirmAction: 'Confirm Action',
    runSnapshot: 'Run Full Analysis',
    archiveHistory: 'Data Archive History',
    payloadGenerated: 'Internal Data Generated',
    supportGateStatus: 'Security Status',
    grantSupport: 'Grant Access',
    revokeSupport: 'Revoke Access',
    partialPaymentDirect: 'Go to Ledger',
    receivableDirect: 'Go to Sales Manifest',
    broadcastWhatsApp: 'Broadcast via WhatsApp',
    downloadPayload: 'Download Data',
    addRecord: 'Add Record',
    back: 'Back',
    commanderInterface: 'Order Interface',

    // Auth
    loginGateway: 'Secure Login',
    commandGateway: 'Administrative Access',
    identityRequest: 'New User Request',
    registerNode: 'Create Account',
    initializeSession: 'Sign In',
    initializeInterface: 'Enter Dashboard',
    fullIdentity: 'Authorized Name',
    fullName: 'Full Name',
    systemId: 'Personal ID',
    password: 'Password',
    accessRequest: 'Access Requested',
    awaitingClearance: 'Awaiting Admin Approval',
    authorizeAccess: 'Approve Access',
    requestIdentity: 'Create New Account',
    resumeSession: 'Back to Login',
    accessDenied: 'Access Denied: Invalid Credentials',
    pendingClearance: 'Pending: Admin Approval Required',
    accountSequestered: 'Access Revoked: Contact Admin',
    protocolError: 'Error: All fields are required',
    handleUnavailable: 'ID Unavailable: Already in use',
    requestSubmitted: 'Success: Request submitted for approval',

    // Dashboard
    assetManifest: 'Total Assets',
    liquidityDelta: 'Revenue Flow',
    retentionCredit: 'Client Credit',
    liabilityIndex: 'Unpaid Debt',
    allProtocolsNominal: 'System Status: Active',
    systemWarning: 'Warning: Low Stock',
    systemAlert: 'Alert: Immediate Action',
    totalValuation: 'Portfolio Value',
    reserveLow: 'Low Stock',
    reserveOptimal: 'Optimal Stock',

    // Sales / Transactions
    transactionPortal: 'Transaction Portal',
    exchangeDate: 'Transaction Date',
    assetDetail: 'Product Name',
    entityInfo: 'Client Name',
    transactionVal: 'Total Amount',
    settledAmount: 'Amount Paid',
    varianceTip: 'Adjust Balance',
    recordExchange: 'Add Sale',
    unitsSold: 'Quantity',
    totalRevenue: 'Total Revenue',

    // Stock / Inventory
    assetIdentity: 'Product Name',
    sector: 'Category',
    reserve: 'Quantity',
    unitRate: 'Unit Price',
    valuation: 'Total Value',
    optimal: 'In Stock',
    low: 'Almost Depleted',
    depleted: 'Out of Stock',

    // Reports / Intelligence
    projectTracker: 'Financial Tracking',
    plannedValue: 'Projected Revenue',
    actualValue: 'Actual Revenue',
    targetStock: 'Target Stock',
    actualStock: 'Available Units',
    grossMargin: 'Net Margin',
    assetLiquidity: 'Liquidity',

    // Ledger / Settlement
    ledgerAudit: 'Ledger Audit',
    manualEntry: 'New Entry',
    debit: 'Expense',
    credit: 'Sale',
    outstandingObligation: 'Financial Obligations',
    financialNodes: 'Operational Accounts',
    accountActivity: 'Transaction History',

    // Wait / Retention
    retention: 'Client Credit',
    protocol: 'Management',
    creditRetention: 'Client Balances',
    loyaltyProgram: 'Loyalty Program',

    // Admin / Recovery
    governance: 'Staff Management',
    masterSettlement: 'Global Accounts',
    provisionIdentity: 'User Provisioning',
    clearance: 'Role',
    identityIdentity: 'Staff Name',
    authorize: 'Approve',
    entityIdentity: 'Username',
    provision: 'Status',
    supportAccess: 'System Support',
    grantAccess: 'Grant Admin Access',
    revokeAccess: 'Revoke Access',
    clearanceEnabled: 'Support: ENABLED',
    clearanceDisabled: 'Support: DISABLED',

    // Common
    date: 'Date',
    status: 'Status',
    action: 'Action',
    search: 'Search records...',
    cancel: 'Cancel',
    execute: 'Confirm',
    abort: 'Abort',
    all: 'All Time',
    today: 'Today',
    month: 'This Month',
    custom: 'Custom Range',
    active: 'Active',
    pending: 'Pending',
    restricted: 'Inactive',
    quantumSecured: 'Secured Access',
    masterClearance: 'System Ver. 4.0',

    // New Luxury Features
    clientsDatabase: 'Client Database',
    spoilage: 'Report a Loss (Spoilage)',
    thermalReceipt: 'Cash Receipt (80mm)',
    closeRegister: 'Close Register',
    printReceipt: 'Print Receipt',
    spoilageReason: 'Reason for loss (e.g. Expired)',
    expectedCash: 'Expected Cash',
    actualCash: 'Actual Cash (Drawer)',
    cashDiscrepancy: 'Cash Discrepancy',
    vipStatus: 'VIP Client',
    riskStatus: 'Financial Risk',
    commanderCenter: 'Command Center',
    forecasting: 'AI Forecasting',
    leaderboard: 'Performance Leaderboard',
    riskRoom: 'Critical Risk Zone',
    projectedRevenue: 'Projected Revenue (7d)',
    efficiencyIndex: 'Efficiency Index',
    topOperator: 'Top Operator',
    performanceDelta: 'Performance Variance',
    newSale: 'New Sale',
    todayRevenue: 'Today\'s Revenue',
    totalTransactions: 'Total Transactions',
    records: 'Records',
    currentShift: 'Current Shift',
    allShifts: 'All Shifts',
    confirmSale: 'Confirm Sale',
    confirm: 'Confirm',
    success: 'Success',
    transactionRecorded: 'Transaction recorded successfully',
    print: 'Print',
    share: 'Share',
    intelligence: 'Business Intelligence',
    auditor: 'Multi-Sector Auditor',
    sectors: 'Sectors',
    salesSec: 'Sales',
    ledgerSec: 'Ledger',
    stockSec: 'Stock',
    lossesSec: 'Losses',
    pdf: 'PDF',
    revenue: 'Sales Revenue',
    debtsIssued: 'Debts Issued',
    netMargin: 'NET MARGIN'
  },
  fr: {
    // Navigation & Branding
    dashboard: 'Vue d\'Ensemble',
    stock: 'Gestion des Stocks',
    sales: 'Opérations de Vente',
    waitSystem: 'Gestion des Crédits',
    ledger: 'Grand Livre',
    admin: 'Contrôle Système',
    logOut: 'Déconnexion',
    liveSync: 'Synchronisation',
    searchPlaceholder: 'Rechercher un actif...',
    inventoryHeader: 'Gestion des Stocks',
    commandInterface: 'Console de Gestion',
    systemArchitecture: 'Cadre Opérationnel',
    operationalDiagnostics: 'Dossiers Système',
    confirmAction: 'Confirmer l\'Action',
    runSnapshot: 'Exécuter un Analyse Complète',
    archiveHistory: 'Historique des Archives Data',
    payloadGenerated: 'Données Internes Générées',
    supportGateStatus: 'Statut de Sécurité',
    grantSupport: 'Accorder l\'Accès',
    revokeSupport: 'Révoquer l\'Accès',
    partialPaymentDirect: 'Aller au Grand Livre',
    receivableDirect: 'Aller au Manifeste des Ventes',
    broadcastWhatsApp: 'Diffuser via WhatsApp',
    downloadPayload: 'Télécharger les Données',
    addRecord: 'Enregistrer une Entrée',
    back: 'Retour',
    commanderInterface: 'Interface de Commande',
    
    // Auth
    loginGateway: 'Connexion Sécurisée',
    commandGateway: 'Accès Administratif',
    identityRequest: 'Demande de Nouvel Utilisateur',
    registerNode: 'Créer un Compte',
    initializeSession: 'Se Connecter',
    initializeInterface: 'Entrer dans le Tableau de Bord',
    fullIdentity: 'Nom Autorisé',
    fullName: 'Nom Complet',
    systemId: 'Identifiant Personnel',
    password: 'Mot de Passe',
    accessRequest: 'Accès Demandé',
    awaitingClearance: 'En Attente d\'Approbation Administrative',
    authorizeAccess: 'Approuver l\'Accès',
    requestIdentity: 'Créer un Nouveau Compte',
    resumeSession: 'Retour à la Connexion',
    accessDenied: 'Accès Refusé : Identifiants Invalides',
    pendingClearance: 'En Attente : Approbation Admin Requise',
    accountSequestered: 'Accès Révoqué : Contacter l\'Admin',
    protocolError: 'Erreur : Tous les champs sont requis',
    handleUnavailable: 'Identifiant Indisponible : Déjà utilisé',
    requestSubmitted: 'Succès : Demande envoyée pour approbation',
    
    // Dashboard
    assetManifest: 'Total des Actifs',
    liquidityDelta: 'Flux de Revenus',
    retentionCredit: 'Crédit Client',
    liabilityIndex: 'Dette Impayée',
    allProtocolsNominal: 'Statut Système : Actif',
    systemWarning: 'Avertissement : Stock Faible',
    systemAlert: 'Alerte : Action Immédiate',
    totalValuation: 'Valeur du Portefeuille',
    reserveLow: 'Stock Faible',
    reserveOptimal: 'Stock Optimal',
    
    // Sales / Transactions
    transactionPortal: 'Portail des Transactions',
    exchangeDate: 'Date de Transaction',
    assetDetail: 'Nom du Produit',
    entityInfo: 'Nom du Client',
    transactionVal: 'Montant Total',
    settledAmount: 'Montant Payé',
    varianceTip: 'Ajuster le Solde',
    recordExchange: 'Ajouter une Vente',
    unitsSold: 'Quantité',
    totalRevenue: 'Chiffre d\'Affaires',
    
    // Stock / Inventory
    assetIdentity: 'Nom du Produit',
    sector: 'Catégorie',
    reserve: 'Quantité',
    unitRate: 'Prix Unitaire',
    valuation: 'Valeur Totale',
    optimal: 'En Stock',
    low: 'Presque Épuisé',
    depleted: 'Rupture de Stock',
    
    // Reports / Intelligence
    projectTracker: 'Suivi Financier',
    plannedValue: 'Revenus Projetés',
    actualValue: 'Revenus Réalisés',
    targetStock: 'Stock Cible',
    actualStock: 'Unités Disponibles',
    grossMargin: 'Marge Nette',
    assetLiquidity: 'Liquidité',
    
    // Ledger / Settlement
    ledgerAudit: 'Audit du Grand Livre',
    manualEntry: 'Nouvelle Entrée',
    debit: 'Dépense',
    credit: 'Vente',
    outstandingObligation: 'Obligations Financières',
    financialNodes: 'Comptes Opérationnels',
    accountActivity: 'Historique des Transactions',

    // Wait / Retention
    retention: 'Crédit Client',
    protocol: 'Gestion',
    creditRetention: 'Soldes Clients',
    loyaltyProgram: 'Programme de Fidélité',

    // Admin / Recovery
    governance: 'Gestion du Personnel',
    masterSettlement: 'Comptes Globaux',
    provisionIdentity: 'Provisionnement des Utilisateurs',
    clearance: 'Rôle',
    identityIdentity: 'Nom du Personnel',
    authorize: 'Approuver',
    entityIdentity: 'Nom d\'Utilisateur',
    provision: 'Statut',
    supportAccess: 'Support Système',
    grantAccess: 'Accorder l\'Accès Admin',
    revokeAccess: 'Révoquer l\'Accès',
    clearanceEnabled: 'Support : ACTIVÉ',
    clearanceDisabled: 'Support : DÉSACTIVÉ',
    
    // Common
    date: 'Date',
    status: 'Statut',
    action: 'Action',
    search: 'Rechercher des archives...',
    cancel: 'Annuler',
    execute: 'Confirmer',
    abort: 'Abandonner',
    all: 'Tout le Temps',
    today: 'Aujourd\'hui',
    month: 'Ce Mois',
    custom: 'Période',
    active: 'Actif',
    pending: 'En Attente',
    restricted: 'Inactif',
    quantumSecured: 'Accès Sécurisé',
    masterClearance: 'Système Ver. 4.0',

    // New Luxury Features
    clientsDatabase: 'Base Clients VIP',
    spoilage: 'Déclarer une Perte (Avarie)',
    thermalReceipt: 'Ticket Caisse (80mm)',
    closeRegister: 'Clôture de Caisse',
    printReceipt: 'Imprimer Reçu',
    spoilageReason: 'Raison de la perte (Ex: Pourri)',
    expectedCash: 'Espèces Attendues',
    actualCash: 'Espèces Réelles (Tiroir)',
    cashDiscrepancy: 'Écart de Caisse',
    vipStatus: 'Client VIP',
    riskStatus: 'Risque Financier',
    commanderCenter: 'Centre de Commande',
    forecasting: 'Prévisions I.A',
    leaderboard: 'Palmarès de Performance',
    riskRoom: 'Zone de Risque Critique',
    projectedRevenue: 'Revenu Projeté (7j)',
    efficiencyIndex: 'Indice d\'Efficacité',
    topOperator: 'Meilleur Opérateur',
    performanceDelta: 'Variation de Performance',
    newSale: 'Nouvelle Vente',
    todayRevenue: 'Chiffre d\'Affaires du Jour',
    totalTransactions: 'Transactions Totales',
    records: 'Enregistrements',
    currentShift: 'Poste Actuel',
    allShifts: 'Tous les Postes',
    confirmSale: 'Confirmer la Vente',
    confirm: 'Confirmer',
    success: 'Succès',
    transactionRecorded: 'Transaction enregistrée avec succès',
    print: 'Imprimer',
    share: 'Partager',
    intelligence: 'Intelligence d\'Affaires',
    auditor: 'Auditeur Multi-Secteurs',
    sectors: 'Secteurs',
    salesSec: 'Ventes',
    ledgerSec: 'Grand Livre',
    stockSec: 'Stock',
    lossesSec: 'Pertes',
    pdf: 'PDF',
    revenue: 'Revenus des Ventes',
    debtsIssued: 'Dettes Émises',
    netMargin: 'MARGE NETTE'
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem('biztrack_lang') || 'en');

  const toggleLang = () => {
    const next = lang === 'en' ? 'fr' : 'en';
    setLang(next);
    localStorage.setItem('biztrack_lang', next);
  };

  const t = (key) => (translations[lang] && translations[lang][key]) || translations.en[key] || key;
  const L = (en, fr) => lang === 'fr' ? fr : en;

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t, L }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
